# docker automatically reads .env file
# docker version
version: '3.8'

# what are the containers that we want to run
services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: bible_postgres

    # environment variables for the container
    environment:
      # name of the db
      POSTGRES_DB: ${POSTGRES_DB}

      # credentials for the db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      # allows us to log in without password for local dev
      POSTGRES_HOST_AUTH_METHOD: trust

    # port of my machine : port of the container
    ports:
      - "${POSTGRES_PORT}:5432"

    # standard setup for posgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/docker-data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:

    build:
      context: ./app
      dockerfile: Dockerfile

    container_name: bible_flask_app

    ports:
      - "5000:5000"

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432

    depends_on:
      postgres:
        condition: service_healthy
        
    restart: unless-stopped
    volumes:
      - ./app:/app

volumes:
  postgres_data: